name: "Pull Request Labeler"
on:
  pull_request_target:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    permissions:
      contents: read       # Read repository contents for glob matching
      pull-requests: write # Apply labels to pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
